Let's make the challenge a bit more complex by adding more filtering criteria and calculations. We will also provide a larger dataset in the form of a dictionary, which can be converted into a Pandas DataFrame.

**Updated Challenge:**

1. Select only the rows where the crop type is either "Wheat", "Corn", or "Rice".
2. Filter the data to only include rows where:
   - The average temperature is between 15°C and 35°C.
   - Rainfall is greater than 50 mm.
   - The soil type is either "Loam" or "Clay".
3. Create a new column called "Yield_Potential," calculated as: 
   (Rainfall * 0.4 + Temperature * 1.2 - Pollution_Level * 0.3).
4. Add a new column "Above_Average_Yield," where the value is `True` if "Yield_Potential" is greater than the average yield for that crop type across all rows.
5. Group the data by "Crop_Type" and "Soil_Type" and calculate the average "Yield_Potential" for each group.
6. Sort the resulting DataFrame by "Yield_Potential" in descending order.
7. Filter the data further by selecting only those rows where the pollution level is less than 30.

**Sample Dictionary Dataset (with 100 rows):**

```python
data = {
    'Crop_Type': ['Wheat', 'Corn', 'Rice'] * 34 + ['Wheat', 'Corn'],
    'Temperature': [20, 25, 30, 17, 22, 29, 18, 21, 32, 16, 24, 31] * 8 + [19, 26],
    'Rainfall': [60, 80, 100, 55, 75, 95, 62, 82, 102, 58, 78, 98] * 8 + [65, 85],
    'Soil_Type': ['Clay', 'Loam', 'Sandy', 'Clay', 'Loam', 'Sandy', 'Clay', 'Loam', 'Sandy', 'Clay', 'Loam', 'Sandy'] * 8 + ['Clay', 'Loam'],
    'Pollution_Level': [20, 25, 35, 15, 30, 45, 22, 28, 38, 19, 26, 36] * 8 + [23, 27]
}
```

This dataset has 100 rows, and you can load it using Pandas like this:

```python
import pandas as pd

df = pd.DataFrame(data)
```

### Notes:
- The dictionary `data` has repeating entries for three crop types ("Wheat", "Corn", and "Rice") with varying values for temperature, rainfall, soil type, and pollution level.
- The challenge is now more complex with additional filtering, grouping, and calculations.
- The dataset includes pollution levels, which add another layer to the yield potential calculation and final filtering.

Feel free to give it a try! Let me know if you'd like any clarifications along the way.

In [1]:
import pandas as pd
import warnings
warnings.simplefilter("ignore")

In [2]:
data = {
    'Crop_Type': ['Wheat', 'Corn', 'Rice'] * 34 + ['Wheat', 'Corn'],
    'Temperature': [20, 25, 30, 17, 22, 29, 18, 21, 32, 16, 24, 31, 19] * 8,
    'Rainfall': [60, 80, 100, 55, 75, 95, 62, 82, 102, 58, 78, 98, 76] * 8,
    'Soil_Type': ['Clay', 'Loam', 'Sandy', 'Clay', 'Loam', 'Sandy', 'Clay', 'Loam', 'Sandy', 'Clay', 'Loam', 'Sandy', 'Clay'] * 8,
    'Pollution_Level': [20, 25, 35, 15, 30, 45, 22, 28, 38, 19, 26, 36, 23] * 8
}

In [9]:
def wrangle(data):
    df = pd.DataFrame.from_dict(data)

    crop_type = ["Wheat", "Corn", "Rice"]
    df = df.query('Crop_Type in @crop_type')

    #The average temperature is between 15°C and 35°C.
    df = df[(df["Temperature"] > 15) & (df["Temperature"] < 35)]
    
    #Rainfall is greater than 50 mm.
    df = df[(df["Rainfall"] > 50)]
    
    #The soil type is either "Loam" or "Clay".
    soil_type = ["Loam", "Clay"]
    df = df.query('Soil_Type in @soil_type')

    df["Yield_Potential"] = df["Rainfall"] * 0.4 + df["Temperature"] * 1.2 - df["Pollution_Level"] * 0.3
    
    df["Above_Average_Yield"] = df["Yield_Potential"] > df["Yield_Potential"].mean()
    
    return df

df = wrangle(data)
df.head(5)

,Crop_Type,Temperature,Rainfall,Soil_Type,Pollution_Level,Yield_Potential,Above_Average_Yield
0,Wheat,20,60,Clay,20,42.0,False
1,Corn,25,80,Loam,25,54.5,True
3,Wheat,17,55,Clay,15,37.9,False
4,Corn,22,75,Loam,30,47.4,True
6,Wheat,18,62,Clay,22,39.8,False

In [18]:
#Group the data by "Crop_Type" and "Soil_Type" and calculate the average "Yield_Potential" for each group.
df.groupby(["Crop_Type", "Soil_Type"])["Yield_Potential"].mean()

Crop_Type  Soil_Type
Corn       Clay         40.540
           Loam         50.925
Rice       Clay         40.540
           Loam         50.925
Wheat      Clay         40.540
           Loam         50.925
Name: Yield_Potential, dtype: float64

In [20]:
#Group the data by "Crop_Type" and "Soil_Type" and calculate the average "Yield_Potential" for each group.
df.sort_values("Yield_Potential", ascending = False)

,Crop_Type,Temperature,Rainfall,Soil_Type,Pollution_Level,Yield_Potential,Above_Average_Yield
92,Rice,25,80,Loam,25,54.5,True
27,Wheat,25,80,Loam,25,54.5,True
79,Corn,25,80,Loam,25,54.5,True
66,Wheat,25,80,Loam,25,54.5,True
1,Corn,25,80,Loam,25,54.5,True
...,...,...,...,...,...,...,...
48,Wheat,16,58,Clay,19,36.7,False
22,Corn,16,58,Clay,19,36.7,False
87,Wheat,16,58,Clay,19,36.7,False
74,Rice,16,58,Clay,19,36.7,False
61,Corn,16,58,Clay,19,36.7,False

In [22]:
df[df.sort_values("Yield_Potential", ascending = False)["Pollution_Level"] < 30]

,Crop_Type,Temperature,Rainfall,Soil_Type,Pollution_Level,Yield_Potential,Above_Average_Yield
0,Wheat,20,60,Clay,20,42.0,False
1,Corn,25,80,Loam,25,54.5,True
3,Wheat,17,55,Clay,15,37.9,False
6,Wheat,18,62,Clay,22,39.8,False
7,Corn,21,82,Loam,28,49.6,True
...,...,...,...,...,...,...,...
97,Corn,18,62,Clay,22,39.8,False
98,Rice,21,82,Loam,28,49.6,True
100,Corn,16,58,Clay,19,36.7,False
101,Rice,24,78,Loam,26,52.2,True
103,Corn,19,76,Clay,23,46.3,True